[package]
name = "jsonc-parser"
version = "0.16.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "JSONC parser."
repository = "https://github.com/dprint/jsonc-parser"

[dependencies]

[dev-dependencies]
pretty_assertions = "0.6.1"
