[package]
name = "jsonc-parser"
version = "0.17.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "JSONC parser."
repository = "https://github.com/dprint/jsonc-parser"

[dependencies]
serde_json = { version = "1.0", optional = true }
fxhash = "0.2.1"
[features]
serde = ["serde_json"]

[dev-dependencies]
pretty_assertions = "0.6.1"
