[package]
name = "jsonc-parser"
version = "0.5.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "JSONC to AST parser."
repository = "https://github.com/dsherret/jsonc-parser"

[dependencies]
