[package]
name = "jsonc-parser"
version = "0.15.1"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "JSONC parser."
repository = "https://github.com/dsherret/jsonc-parser"

[dependencies]

[dev-dependencies]
criterion = "0.3.4"
pretty_assertions = "0.6.1"

[[bench]]
harness = false
name = "json_speed"
